Here you go, Jefferson—the entire PLATO-driven Katello build wrapped into one clean, self-contained Ansible playbook.

---

### 📦 `katello-day0.yml` (Your all-in-one YML for root of repo)

```yaml
---
- name: PLATO-Driven Katello 3.11.5 Deployment on OL9
  hosts: katello
  become: true
  vars:
    cert_file: /etc/candlepin/certs/keystore.p12
    cert_source: ./keystore.p12

  tasks:

    - name: Enable EPEL and Foreman/Katello repos
      yum:
        name:
          - https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm
          - https://yum.theforeman.org/releases/3.11/el9/x86_64/foreman-release.rpm
          - https://yum.theforeman.org/katello/4.13/katello-repos-latest.el9.noarch.rpm
        state: present

    - name: Install Katello installer package
      dnf:
        name: foreman-installer-katello
        state: present

    - name: Ensure firewalld is running
      service:
        name: firewalld
        state: started
        enabled: true

    - name: Open required ports
      firewalld:
        port: "{{ item }}/tcp"
        permanent: yes
        immediate: yes
        state: enabled
      loop:
        - 443
        - 80
        - 9090
        - 5647
        - 8140

    - name: Copy prebuilt keystore cert
      copy:
        src: "{{ cert_source }}"
        dest: "{{ cert_file }}"
        mode: '0600'
        owner: root
        group: root

    - name: Check for existing Candlepin DB
      shell: |
        psql -U postgres -tc "SELECT 1 FROM pg_database WHERE datname='candlepin'" | grep -q 1
      register: candlepin_exists
      ignore_errors: true

    - name: Optional pause before DB reset
      pause:
        prompt: "Candlepin DB exists. Press ENTER to drop or CTRL+C to abort."
      when: candlepin_exists.rc == 0

    - name: Drop Candlepin DB
      shell: psql -U postgres -c "DROP DATABASE IF EXISTS candlepin;"
      when: candlepin_exists.rc == 0

    - name: Drop Foreman DB
      shell: psql -U postgres -c "DROP DATABASE IF EXISTS foreman;"
      when: candlepin_exists.rc == 0

    - name: Run foreman-installer with Katello scenario
      command: foreman-installer --scenario katello
      args:
        creates: /etc/foreman-installer/scenarios.d/katello-answers.yaml
```

---

### 📝 Instructions

- **Save this as** `katello-day0.yml` in your repo root.
- Place your `keystore.p12` alongside it or adjust the `cert_source` path.
- Add a minimal `inventory` file, like:
  ```ini
  [katello]
  localhost ansible_connection=local
  ```

- Then run:
  ```bash
  ansible-playbook -i inventory katello-deploy.yml
  ```

